apiVersion: v1
kind: Service
metadata:
  name: devops-project
  labels:
    app: devops-project
    service: devops-project
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: devops-project
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-project-service
  labels:
    account: devops-project
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-v1
  labels:
    app: devops-project
    version: v1
spec:
  replicas : 1
  selector:
    matchLabels:
      app: devops-project
      version: v1
  template:
    metadata:
      labels:
        app: devops-project
        version: v1
    spec:
      serviceAccountName: devops-project-service
      containers:
      - name: devops-project
        image: alexiscapon/devops-project
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-v2
  labels:
    app: devops-project
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
      version: v2
  template:
    metadata:
      labels:
        app: devops-project
        version: v2
    spec:
      serviceAccountName: devops-project-service
      containers:
      - name: devops-project
        image: alexiscapon/devops-project-v2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
        securityContext:
          runAsUser: 1000
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
---